# Generated by Django 3.1.6 on 2021-03-30 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('reaction', models.CharField(choices=[('O', 'Love'), ('L', 'Like'), ('D', 'Dislike'), ('H', 'Hate')], default='O', max_length=1)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pin')),
            ],
        ),
    ]
