# Generated by Django 3.1.6 on 2021-04-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pins',
            field=models.ManyToManyField(to='main_app.Pin'),
        ),
    ]
